# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_remove_leaderboard_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='playtime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.CharField(default='No Name Loser', max_length=50),
        ),
    ]
