# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_auto_20161221_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='cheated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='cheated_reason',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='levels_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='playtime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
